### ISSUE TITLE
BUG: not working if there are unlabeled containers around

### ISSUE THREAD

**Issue by dimaip** [funkyfuture/deck-chores#2]
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock funkyfuture/deck-chores
Deck Chores 0.1.beta2 started.
2016-12-22 13:58:50,373|ERROR   |Caught unhandled exception:
2016-12-22 13:58:50,373|ERROR   |'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/deck_chores-0.1b2-py3.6.egg/deck_chores/main.py", line 178, in main
    if there_is_another_deck_chores_container(cfg.client):
  File "/usr/local/lib/python3.6/site-packages/deck_chores-0.1b2-py3.6.egg/deck_chores/main.py", line 36, in there_is_another_deck_chores_container
    if labels.get('org.label-schema.name', '') == 'deck-chores':
AttributeError: 'NoneType' object has no attribute 'get'
```

I have a lot of containers without labels. Could that be a problem?

Ubuntu 15, Docker 1.12.1.

**Comment by funkyfuture** [comment]
Thanks for reporting, the fix should included in the image with the `dev` tag in a few seconds.
