### ISSUE TITLE
Issue with checking container StartedAt values

### ISSUE THREAD

**Issue by zxpower** [funkyfuture/deck-chores#66]
It could happen that container is started with quite precise timing and its `StartedAt` returns sting shorter than expeced by `inspect_running_containers()` function here: https://github.com/funkyfuture/deck-chores/blob/538d9f52b25c18cf36bb4c9aedc97e438fb9ec0e/deck_chores/main.py#L104 therefore causing endless loop of container restarting with this error:

```
Deck Chores 1.1.7 started.
2021-03-08 14:33:18,567|INFO    |Inspecting running containers.
2021-03-08 14:33:18,628|ERROR   |Caught unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 300, in main
    last_event_time = inspect_running_containers()
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 104, in inspect_running_containers
    datetime.fromisoformat(data['State']['StartedAt'][:26]),  # type: ignore
ValueError: Invalid isoformat string: '2021-03-06T21:58:12.7094Z'
```

Deck Chores version used: `v1.1.7`

Suggested actions:
- check only full seconds
- output container name that's causing issues so it could be restarted manually

**Comment by funkyfuture** [comment]
thanks for reporting!
