### ISSUE TITLE
TypeError on start with 1.1.12

### ISSUE THREAD

**Issue by prilka** [funkyfuture/deck-chores#72]
Since version 1.1.12 this error is triggered on container start.

```
Deck Chores 1.1.12 started.
2021-05-25 10:32:25,260|INFO    |Inspecting running containers.
2021-05-25 10:32:25,272|ERROR   |Caught unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 301, in main
    last_event_time = inspect_running_containers()
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 101, in inspect_running_containers
    last_event_time = max(
TypeError: can't compare offset-naive and offset-aware datetimes
```

Minimal command to reproduce:
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock funkyfuture/deck-chores:1
```

This error does not occur in version 1.1.11

**Comment by funkyfuture** [comment]
thanks for reporting. i retracted that release and a fix will be released asap.

**Comment by funkyfuture** [comment]
sorry for any inconvenience, the 1.1.13 release is out.
